### ISSUE TITLE
Help Me!

### ISSUE THREAD

**Issue by SfenKer** [TrySzymeko/VasteCord-1.0#3]
Hello,
How fix this error in code? Because I watched 100 tutorials by Mięta and still i can't fix!

![unknown](https://user-images.githubusercontent.com/48128694/119474516-861ace80-bd4c-11eb-9f7d-b2d223fcd396.png)

**Comment by TrySzymeko** [comment]
Src udostępnione ale bez plikow mavena dlatego bledy!#!##!
