### ISSUE TITLE
Siema prosimy nauczyc sie javy

### ISSUE THREAD

**Issue by narumii** [TrySzymeko/VasteCord-1.0#4]
Dostalem raka od samego kodu to co tu sie odpierdala to istna poezja, zajebisty nullping check wzieles chyba za bardzo do siebie nulle 😂 Zajebisty singleton w tym loaderze pro java dev doslownie. VPN check wyglada jak gowno z fernflowera smiszne troche.

Jak juz chcesz robic projekty na githuba wypadaloby nauczyc sie podstaw javy:
- https://javastart.pl/
- https://www.tutorialspoint.com/java/index.htm

Edit: Predzej uzylbym botfiltera z pluginem na fix handshake crashera niz tego
Boje sie o to jak wyglada ten avarionspigot.

**Comment by TrySzymeko** [comment]
nie płacz :(

**Comment by TrySzymeko** [comment]
Skoro ci się coś nie podoba to nie używaj??? Tak tak zwany "VPN check" jest zajebany z githuba wiec fajny fernflower

Co do "Jak juz chcesz robic projekty na githuba wypadaloby nauczyc sie podstaw javy:" a pokazać ci kod natsuki???

**Comment by narumii** [comment]
```
    private static VasteLoader loader;
   
    public VasteLoader() {
        this.blacklistManager = new BlacklistManager();
        this.connectionManager = new ConnectionManager();
        this.taskManager = new TaskManager();
        loader = this;
    }


    public static VasteLoader getLoader() {

        if(loader == null){
            new VasteLoader();
        }

        return loader;
    }
```
Kozacki singleton kiedy nauczysz sie podstaw javy??

https://github.com/TrySzymeko/VasteCord-1.0/blob/master/proxy/src/main/java/me/project/vaste/cord/conf/VasteCordConfiguraion.java YYYYY to samo mialem jak to zobaczylem

Widac nawet dobrego vpn checka sam nie potrafisz zrobic to trzeba zajebac jakies gowno. (I napierdalac instancja AntiProxyManagera co sprawdzenie adresu 😂 )

```
    @Override
    public void handle(PacketWrapper packet) throws Exception
    {

        SocketAddress remoteAddress = this.channel.getHandle().remoteAddress();
        InetAddress address = ((InetSocketAddress)remoteAddress).getAddress();
        VasteLoader.getLoader().getConnectionManager().checkAddress(address);
        if (packet == null || packet.packet == null) {
            this.channel.close();
            VasteLoader.getLoader().getBlacklistManager().addToBlacklist(address, "NullPingCrash");
        }

```
Imagine robic "fixy" na handshake crashery nie wiedzac jak dzialaja handshake crashery XDDD

```
                    if (cause instanceof CorruptedFrameException) {

                        SocketAddress remoteAddress = channel.getHandle().remoteAddress();
                        InetAddress address = ((InetSocketAddress) remoteAddress).getAddress();
                        VasteLoader.getLoader().getBlacklistManager().addToBlacklist(address, "Corrupted frame");
                        if (VasteLoader.getLoader().getConfig().isClean_console()) {
                            ProxyServer.getInstance().getLogger().log(Level.WARNING, "{0} - corrupted frame: {1}", new Object[]
                                    {
                                            handler, cause.getMessage()
                                    });
                        }
                    }
```
Kolejny mem

Czekam pokazuj kod natsuki tylko ktorego natsuki?? XD tego co bylo na githubie a sorry czekaj zostalo wyjebane :(
A jak chcesz do mnie jebany kidzie podskakiwac to moze wyjasnij kod moich aktualnych projektow. Tylko bedzie z tym problem bo chuja potrafisz :(

**Comment by narumii** [comment]
"a pokazać ci kod natsuki???" chyba sie nie doczekam :(
"A jak chcesz do mnie jebany kidzie podskakiwac to moze wyjasnij kod moich aktualnych projektow. Tylko bedzie z tym problem bo chuja potrafisz :(" tego tym bardziej :(

**Comment by TrySzymeko** [comment]
Ta kurwa nie odczekasz się ale włączenia twojego mózgu

**Comment by narumii** [comment]
Dokladnie poprostu jest to dla ciebie zbyt trudne i tego nie zrobisz, kocham jak jakies pseudole groza/mowia komus ze cos zrobia ale okazuje sie ze sa zbyt obsrani aby cos zrobic :(
