### ISSUE TITLE
Napraw swoj mozg

### ISSUE THREAD

**Issue by narumii** [TrySzymeko/VasteCord-1.0#5]
Widac dupa piecze ;) 

![image](https://user-images.githubusercontent.com/57463654/120119146-5f1e2b80-c196-11eb-96e8-9b641b75a144.png)
![image](https://user-images.githubusercontent.com/57463654/120119150-62191c00-c196-11eb-9081-f2d06e0070cd.png)
![image](https://user-images.githubusercontent.com/57463654/120119151-63e2df80-c196-11eb-8b50-eb42784d6d25.png)
![image](https://user-images.githubusercontent.com/57463654/120119153-65aca300-c196-11eb-92ab-5d50c7e744af.png)

**Comment by TrySzymeko** [comment]
o chuj ci chodzi nie bedziesz mi gówna pisał tutaj jak masz coś do powiedzienia to zapraszam na discorda

**Comment by narumii** [comment]
ale ten syf jest na githubie nie na dc :( i chce aby kazdy zobaczyl jaki przyjebany jestes oraz ze nawet podstaw javy nie umiesz
